### ISSUE TITLE
Unable to install via MM Console

### ISSUE THREAD

**Issue by uhlhosting** [mattermost/mattermost-plugin-walltime#8]
I am unable to deploy the tar.gz file via plugins in OSX app

**Comment by uhlhosting** [comment]
{"level":"error","ts":1548672844.986692,"caller":"web/context.go:60","msg":"Encountered error extracting plugin","path":"/api/v4/plugins","request_id":"87odcfj5spbejx8psoeb37nqao","ip_addr":"89.103.182.57","user_id":"48bbj6nc97f55npw6br7gxo96h","method":"POST","err_where":"installPlugin","http_code":400,"err_details":"ExtractTarGz: unknown type: 103 in pax_global_header"}

**Comment by hanzei** [comment]
Could you please test the latest release? https://github.com/mattermost/mattermost-plugin-walltime/releases/tag/0.1.1

**Comment by uhlhosting** [comment]
Hi @hanzei 

<img width="477" alt="image" src="https://user-images.githubusercontent.com/6324047/51861844-89991900-233d-11e9-9925-56a95d672b7b.png">

Good news!

Thanks , will provide feedback :)

**Comment by hanzei** [comment]
Closing this one for now.
