### ISSUE TITLE
Cut GitHub release 0.1.1

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-walltime#9]
https://github.com/mattermost/mattermost-plugin-walltime/commit/b8ae159d0f7cd32685be3b514f4c309e9039de13 bumped the version to `0.1.1`. A new GH release should be cut.

@mkraft Mind if I take care of this?

**Comment by cpanato** [comment]
i can take care

**Comment by cpanato** [comment]
done
